- name: install ngnix
  hosts: all
  become: yes
  tasks:
 
    - name: install ngnix
      yum:
        name: nginx
        state: present
      vars:
        ansible_python_interpreter: /usr/bin/python2
      
 
    - name: start and enable ngnix service
      service:
        name: nginx
        state: started
        enabled: true
       